# Generated by Django 5.0.6 on 2024-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='date time modified')),
            ],
        ),
    ]
