# Generated by Django 5.0.6 on 2024-05-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'books', 'verbose_name_plural': 'books'},
        ),
    ]
