# Generated by Django 5.0.6 on 2024-05-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'my users', 'verbose_name_plural': 'my users'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'otp code', 'verbose_name_plural': 'otp code'},
        ),
    ]
